### ISSUE TITLE
RepairTurret 'attempt to index a nil value'

### ISSUE THREAD

**Issue by jameinel** [Klonan/Repair_Turret#1]
I'm trying out RepairTurret with Rampant and Rampant Arsenal. However, I'm running into an error "attempt to index a nil value'

```
Please report this error to the mod author.

Error while running event Repair_Turret::on_tick (ID 0)
__Repair_Turret__/script/repair_turret.lua:326: attempt to index a nil value
stack traceback:
	__Repair_Turret__/script/repair_turret.lua:326: in function 'get_pickup_entity'
	__Repair_Turret__/script/repair_turret.lua:382: in function 'update_turret'
	__Repair_Turret__/script/repair_turret.lua:522: in function 'check_turret_update'
	__Repair_Turret__/script/repair_turret.lua:536: in function 'handler'
	__core__/lualib/event_handler.lua:44: in function <__core__/lualib/event_handler.lua:42>
```

That code seems to be:
https://github.com/Klonan/Repair_Turret/blob/master/script/repair_turret.lua#L326
```
  local owner = pickup_point.owner
  if owner.type == "roboport" then
    stack = owner.get_inventory(defines.inventory.roboport_material).find_item_stack(repair_item)
  else
    stack = owner.get_output_inventory().find_item_stack(repair_item)
  end
```

Now, I don't really know what possible pickup_point or owners are possible.
I wasn't having any trouble until I started placing a Rampant Arsenal Rapid Rocket Turret (mk2).

I have a save that reproduces the issue fairly reliably (within a few seconds if you don't do anything). And I picked up all the rocket turrets and it seems to go back to normal. I don't know if the rocket turret is damaging something the rocket is trying to repair, or if somehow because I placed the rocket turrets last it was trying to use it as the owner.

**Comment by jameinel** [comment]
I suppose another possibility is that I put an inserter down next to the repair turret, but that seems unlikely as picking up the rocket turret but not the inserter causes it to stop crashing.

**Comment by Klonan** [comment]
Can you provide a save game

**Comment by jameinel** [comment]
https://www.dropbox.com/s/wt0mig8xev31cao/Dangerous-20c60.zip?dl=0

Let me know if that works for you. I do have several mods installed, but I
think you can find them from the mod list. When I load that save, it takes
about 10s and then one of the rocket turrets starts firing missiles, and it
crashes. Enough time that if I quickly pick up the rocket turrets it avoids
the crash.  (there is one on the left and one on the right of the box that
I'm standing in).

If I pick up the Repair Turrets it also doesn't crash. But it reliably
crashes with Repair Turret 0.3.7.

**Comment by jameinel** [comment]
Digging through the code it seemed maybe something like a High Explosive
Rocket was calling itself a repair tool, or some other weird thing. But
running debug tooltips I couldn't find anything obvious.

**Comment by Klonan** [comment]
Should be fixed now, seems the turrets were trying to pick up from your character, which has a slightly different inventory layout
