### ISSUE TITLE
logistic network being nil can cause a crash

### ISSUE THREAD

**Issue by BenCat07** [Klonan/Repair_Turret#4]
Hey, sometimes there can be a crash when a logistic network gets destroyed by an explosion for example, and the turrets still tries to place a building. This is the error that you get from it, it is probably a deeper underlying issue.

My base was being attacked on an unprotected flank, and after using atilery to nuke the biters and some of the buildings, this was the crash:
![image](https://user-images.githubusercontent.com/13179138/163676554-f08b7b55-309d-4301-9468-4136e3485aba.png)

**Comment by Klonan** [comment]
I am not sure the exact way it happens, but I added a nil check anyway
